### PR TITLE
Fixed wrong documentation for "auction_update"

### PR DESCRIPTION
**Pull request by tavindev**
The "auction_update" event was represented as the "updated_item" event

### CODE REVIEW

**Comment by Art-em1s** [comment]
auction_update is a different event from updated_item.

The former relates to an update to the auction itself, whereas the latter related to the item being updated.

**Comment by Art-em1s** [comment]
I'll make double check events later though

**Comment by gustavo-dev** [comment]
The data and event name are wrong. The difference between the two events is clear, but they don't share the same data and, definitely, not the same name.

Taken from inspector tools, in Network tab, WS section: 
```javascript
42/trade,["auction_update",…]
0: "auction_update"
1: {id: 28977490, app_id: 730, auction_highest_bid: 39, auction_highest_bidder: 6832812,…}

// Expanded form
{
    app_id: 730
    auction_ends_at: 1639403923
    auction_highest_bid: 39
    auction_highest_bidder: 6832812
    auction_number_of_bids: 10
    id: 28977490
}
```

The documentation referring to the "auction_update" event is the same as the "updated_item" one, even though they're different. That's what the proposed change is addressing 😀

**Comment by Art-em1s** [comment]
Ahh apologies I totally missed that. I'll fix now ty

**Pull request closed without merging**
